# Generated by Django 4.2.20 on 2025-04-29 03:32

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('Male', 'male'), ('Female', 'Female')], max_length=10)),
                ('telephone', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date.today)])),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_telephone', models.PositiveIntegerField()),
                ('home_address', models.CharField(max_length=300)),
                ('Registered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.PositiveIntegerField()),
                ('date_of_sale', models.DateField()),
                ('branch', models.CharField(choices=[('Kalerwe', 'Kalerwe'), ('kireka', 'kireka')], max_length=30)),
                ('customer_name', models.CharField(max_length=300)),
                ('customer_contact', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=300)),
                ('person_responsible', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='estery_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('date_of_purchase', models.DateField()),
                ('branch', models.CharField(choices=[('Kalerwe', 'Kalerwe'), ('kireka', 'kireka')], max_length=30)),
                ('receipt_no', models.CharField(max_length=300)),
                ('supplier_name', models.CharField(max_length=300)),
                ('supplier_contact', models.PositiveIntegerField()),
                ('receipt', models.ImageField(blank=True, upload_to='deposits/%Y/%m/%d')),
                ('person_responsible', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='estery_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=300)),
                ('amount', models.PositiveIntegerField()),
                ('date_of_expense', models.DateField()),
                ('branch', models.CharField(choices=[('Kalerwe', 'Kalerwe'), ('kireka', 'kireka')], max_length=200)),
                ('receipt', models.ImageField(blank=True, upload_to='expenses/%Y/%m/%d')),
                ('person_responsible', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='estery_app.employee')),
            ],
        ),
    ]
