# Generated by Django 4.2.20 on 2025-04-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
