# Generated by Django 4.2.20 on 2025-05-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estery_app', '0002_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cust_name', models.CharField(max_length=255)),
                ('cust_number', models.IntegerField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
