# Generated by Django 4.2.20 on 2025-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estery_app', '0003_imagemodel_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='receipt',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='sales',
            name='cust_number',
            field=models.IntegerField(),
        ),
    ]
