# Generated by Django 4.2.20 on 2025-05-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estery_app', '0004_rename_receipt_purchase_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='receipt',
            new_name='image',
        ),
    ]
